apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: main-builder
  namespace: default
spec:
  serviceAccountName: main-builder-service-account
  tag: stwomack/builder
  stack:
    name: main-clusterstack
    kind: ClusterStack
  store:
    name: main-clusterstore
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
      - id: paketo-buildpacks/nodejs